
class BankAccount
{
public void Populate(long number, decimal balance)
     
        public long Number( )
            {
            return accNo;
            }


        public decimal Balance( )
            {
            return accBal;
            }

        public AccountType Type( )
            {
            return accType;
            }

        public string Type( )
            {
            return accType.ToString( );
            }

//{
//accNo = number;
//accBal = balance;
//accType = AccountType.Checking;
//}
private long accNo;
private decimal accBal;
private AccountType accType;

}
